/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FirmenRouteImport } from './routes/firmen'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClusterRouteImport } from './routes/cluster'
import { Route as BenutzerRouteImport } from './routes/benutzer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClusterIndexRouteImport } from './routes/cluster.index'
import { Route as ClusterNeuRouteImport } from './routes/cluster.neu'
import { Route as ClusterIdRouteImport } from './routes/cluster.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmenRoute = FirmenRouteImport.update({
  id: '/firmen',
  path: '/firmen',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterRoute = ClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const BenutzerRoute = BenutzerRouteImport.update({
  id: '/benutzer',
  path: '/benutzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterIndexRoute = ClusterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClusterRoute,
} as any)
const ClusterNeuRoute = ClusterNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => ClusterRoute,
} as any)
const ClusterIdRoute = ClusterIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClusterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benutzer': typeof BenutzerRoute
  '/cluster': typeof ClusterRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/firmen': typeof FirmenRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/cluster/$id': typeof ClusterIdRoute
  '/cluster/neu': typeof ClusterNeuRoute
  '/cluster/': typeof ClusterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benutzer': typeof BenutzerRoute
  '/dashboard': typeof DashboardRoute
  '/firmen': typeof FirmenRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/cluster/$id': typeof ClusterIdRoute
  '/cluster/neu': typeof ClusterNeuRoute
  '/cluster': typeof ClusterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benutzer': typeof BenutzerRoute
  '/cluster': typeof ClusterRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/firmen': typeof FirmenRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/cluster/$id': typeof ClusterIdRoute
  '/cluster/neu': typeof ClusterNeuRoute
  '/cluster/': typeof ClusterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benutzer'
    | '/cluster'
    | '/dashboard'
    | '/firmen'
    | '/login'
    | '/profil'
    | '/reset-password'
    | '/settings'
    | '/cluster/$id'
    | '/cluster/neu'
    | '/cluster/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benutzer'
    | '/dashboard'
    | '/firmen'
    | '/login'
    | '/profil'
    | '/reset-password'
    | '/settings'
    | '/cluster/$id'
    | '/cluster/neu'
    | '/cluster'
  id:
    | '__root__'
    | '/'
    | '/benutzer'
    | '/cluster'
    | '/dashboard'
    | '/firmen'
    | '/login'
    | '/profil'
    | '/reset-password'
    | '/settings'
    | '/cluster/$id'
    | '/cluster/neu'
    | '/cluster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenutzerRoute: typeof BenutzerRoute
  ClusterRoute: typeof ClusterRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FirmenRoute: typeof FirmenRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmen': {
      id: '/firmen'
      path: '/firmen'
      fullPath: '/firmen'
      preLoaderRoute: typeof FirmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster': {
      id: '/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof ClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benutzer': {
      id: '/benutzer'
      path: '/benutzer'
      fullPath: '/benutzer'
      preLoaderRoute: typeof BenutzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/': {
      id: '/cluster/'
      path: '/'
      fullPath: '/cluster/'
      preLoaderRoute: typeof ClusterIndexRouteImport
      parentRoute: typeof ClusterRoute
    }
    '/cluster/neu': {
      id: '/cluster/neu'
      path: '/neu'
      fullPath: '/cluster/neu'
      preLoaderRoute: typeof ClusterNeuRouteImport
      parentRoute: typeof ClusterRoute
    }
    '/cluster/$id': {
      id: '/cluster/$id'
      path: '/$id'
      fullPath: '/cluster/$id'
      preLoaderRoute: typeof ClusterIdRouteImport
      parentRoute: typeof ClusterRoute
    }
  }
}

interface ClusterRouteChildren {
  ClusterIdRoute: typeof ClusterIdRoute
  ClusterNeuRoute: typeof ClusterNeuRoute
  ClusterIndexRoute: typeof ClusterIndexRoute
}

const ClusterRouteChildren: ClusterRouteChildren = {
  ClusterIdRoute: ClusterIdRoute,
  ClusterNeuRoute: ClusterNeuRoute,
  ClusterIndexRoute: ClusterIndexRoute,
}

const ClusterRouteWithChildren =
  ClusterRoute._addFileChildren(ClusterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenutzerRoute: BenutzerRoute,
  ClusterRoute: ClusterRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FirmenRoute: FirmenRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
